### ISSUE TITLE
Test workflow fails on a new Firefly App

### ISSUE THREAD

**Issue by icaraps** [adobe/aio-apps-action#1]
#### Steps to Reproduce
1. Create a Firefly Project `aio app init` and check options: actions, web assets and CI/CD. 
2. Push your project on Github
3. Edit README.md and open a PR

The PR checks will fail because of 

<img width="800" alt="Screen Shot 2020-05-12 at 3 28 46 PM" src="https://user-images.githubusercontent.com/6012307/81697406-4a74d580-9465-11ea-9776-5c927711856c.png">

Also I noticed that the E2E tests won't run by default. What do you recommend if devs want to include E2E tests into the pipeline ?

**Comment by meryllblanchet** [comment]
@sandeep-paliwal can you investigate?

**Comment by sandeep-paliwal** [comment]
Looking into this

**Comment by sandeep-paliwal** [comment]
Added PR - https://github.com/adobe/aio-apps-action/pull/3
