### ISSUE TITLE
Why use os matrix?

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-apps-action#16]
### Expected Behaviour

Code is executed once on ubuntu-latest.

### Actual Behaviour

os matrix is used, implying that other os' could be added, which will cause the code to run more than once.
The actual action code checks if it is running in ubuntu and will 'do less' if it is not, but it should just not happen.

**Comment by shazron** [comment]
should this issue be in `@adobe/generator-aio-app` repo instead?

**Comment by shazron** [comment]
There are no Github Actions files in this repo. Closing.
