### ISSUE TITLE
Error: The `set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by icaraps** [adobe/aio-apps-action#4]
When running the current GH workflow to deploy an app, there's warning 
```
Error: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
see https://github.com/icaraps/test-firefy-gh-workflow/runs/1357966726#step:6:8

It might come from an underlaying dependency https://github.com/actions/toolkit/search?q=set-env.

**Comment by meryllblanchet** [comment]
Thanks for reporting the warning @icaraps !

@sandeep-paliwal @shazron what do you think?

**Comment by kelvinxzf** [comment]
It is 11/16 that `set-env` will be deprecated now.

`Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/`

**Comment by meryllblanchet** [comment]
Thanks for the update @kelvinxzf . 

cc @sandeep-paliwal @shazron @sarahxxu
