### ISSUE TITLE
Error running action on windows os

### ISSUE THREAD

**Issue by PulkitXChadha** [adobe/aio-apps-action#6]
### Expected Behaviour
Test PR on windows os.

### Actual Behaviour
I get the error below: 

+ jest@26.6.3
added 511 packages from 350 contributors in 38.737s
C:\windows\system32\cmd.exe /D /S /C "C:\npm\prefix\aio.cmd app test"
child_process.js:127
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:127:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:334:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:57:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
 »   Error: Command failed with ENOENT: jest --passWithNoTests ./test
 »   spawn jest ENOENT
Error: The process 'C:\npm\prefix\aio.cmd' failed with exit code 2

#### Steps to Reproduce
Trigger GitHub action on Windows os

**Comment by meryllblanchet** [comment]
Thanks for raising the issue @PulkitXChadha  !

@sandeep-paliwal , could you have a look?

**Comment by sandeep-paliwal** [comment]
Release 1.1.1 should address this problem.
